---
title: "BT2101 GROUP 2"
output: github_document
---

First we load the sheet from Google Forms.
```{r}
library(dplyr)
survey <- read.csv("survey.csv")
head(survey)
```

Then, we proceed to check if someone only fills up only one of the three pre-university scores.
```{r}
check_one_value <- function(row) {
    sum(!is.na(row[c("alevel", "polytechnic", "ib")])) == 1
}

survey <- survey %>% filter(!apply(survey, 1, check_one_value))
head(survey)
```

...and then we convert score rows into numeric values (and then drop those which are NOT numeric)

```{r}
survey$alevel <- as.numeric(survey$alevel)
survey$polytechnic <- as.numeric(survey$polytechnic)
survey$ib <- as.numeric(survey$ib)
```

Now, we do the propensity score matching with a test randion variable
```{r}
library(MatchIt)
survey$aiusebinary <- ifelse(survey$ai_use_freq_rate >= 3.5, 1, 0)
matchOut <- matchit(aiusebinary ~ curr_gpa + y1_gpa + anxiety_rate, data = survey, method = "nearest")
survey_test <- match.data(matchOut)
head(survey_test)
```