name: Generating HTML file for report viewing

on:
  push:
    paths:
      - '*'
  pull:
    paths:
      - '*'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # Or your desired R version

      - name: Install R packages
        run: |
          install.packages(c('rmarkdown'))

      - name: Render R Markdown
        run: Rscript -e "rmarkdown::render('BT2101 RMD.Rmd')" #replace your_document.Rmd

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Re-render R Markdown"
          file_pattern: '*.html'
